# information related to imaging conditions, channels, frequency
[config_groups]
LightPath = "CameraLeft"
objective = "10x"

[device_properties]
Camera-TestProperty1 = 0.05

[imaging]
every_t = 2
exposure = 100
save = true

    [imaging.config_groups]
    # information related to imaging conditions, channels, frequency


# determines channel axis
[channels]
group = "channel"
presets = ["545"]

    # channel specific details, overwrites imaging properties
    [channels.545]
    exposure = 50


# information related to stimulation
[stimulation]
every_t = 1
exposure = 500


# information related to segmentation
[segmentation]
method = "cellpose"
save = true

# all additional arguments are passed to method
model = "cyto3"
diam = 25


# information related to pattern generation
[pattern]
method = "circle"
save = true
rad = 200