from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Protocol


class MicroscopeCoreInterface(Protocol):
    def loadSystemConfiguration(self, configuration): ...

    # SLM-related
    def getSLMDevice(self) -> str: ...
    def getSLMHeight(self, device: str) -> int: ...
    def getSLMWidth(self, device: str) -> int: ...
    def setSLMImage(self, device: str, image: Any) -> None: ...

    # Config/device properties
    def setConfig(self, group: str, config: str) -> None: ...
    def setProperty(self, label: str, name: str, value: Any) -> None: ...
    def getProperty(self, label: str, name: str) -> str: ...
    def getAllowedPropertyValues(
        self, device: str, prop_name: str
    ) -> Sequence[str]: ...
    def describe(self) -> str: ...
    def setFocusDevice(self, label: str) -> None: ...
    def getAvailableConfigGroups(self) -> Sequence[str]: ...
    def getConfigGroupObject(
        self, group: str, include_read_only: bool = False
    ) -> Any: ...

    # Camera-related
    def getCameraDevice(self) -> str: ...
    def setExposure(self, exposure_ms: float) -> None: ...
    def snapImage(self) -> None: ...
    def getImage(self) -> Any: ...
    def getPixelSizeUm(self) -> float: ...
    def getROI(self): ...

    # Stage/focus/positioning
    def getZPosition(self) -> float: ...
    def setPosition(self, z: float) -> None: ...
    def setXYPosition(self, x: float, y: float) -> None: ...
    def setAutoFocusOffset(self, offset: float) -> None: ...

    # Synchronization
    def waitForSystem(self) -> None: ...
