# information related to imaging conditions, channels, frequency
[config_groups]
Objective = "1-Plan Apo LmbdD0.80 20x"
System = "Startup"

[device_properties]


[imaging]
every_t = 1
exposure = 200
save = true
binning = 2

    [imaging.config_groups]
    # information related to imaging conditions, channels, frequency
    Laser-Intensity = "25%"
    LightPath = "Fluor"


# determines channel axis
[channels]
group = "Channel"
presets = ["545", "638"]

    # channel specific details, overwrites imaging properties
    [channels.638]
    exposure = 100
	
	[channels.638.config_groups]
	Laser-Intensity = "50%"
	
	[channels.545]
	exposure = 200
	
	[channels.545.config_groups]
	Laser-Intensity = "10%"


# information related to stimulation
[stimulation]
every_t = 1
exposure = 500
save = false

    [stimulation.config_groups]
    Channel = "DMD"
    LightPath = "DMD"
    Laser-Intensity = "AllOff"
    Sola = "100"


# information related to segmentation
[segmentation]
method = "cellpose"
save = true

# all additional arguments are passed to method
model = "cpsam"
gpu = true


# information related to pattern generation
[pattern]
method = "global_cycle"
period_m = 10
nuc_channel = "545"